# Generated by Django 4.2.7 on 2023-11-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='cover',
            field=models.ImageField(blank=True, default='tasks/task-img.jpg', upload_to='tasks/covers/%Y/%m/%d/'),
        ),
    ]
